# Generated by Django 5.2.1 on 2025-05-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('email', models.EmailField(default='noemail@example.com', max_length=254)),
            ],
        ),
    ]
